Custom background color for negative zoom and drag gestures out of bounds + readme update
ryohey/Zoomable pull request #1
Opened 2023-11-13 11:27 UTC by cdf1982

Hi!

Yours is by far the cleanest implementation online, thank you!

I've taken the liberty to add an optional outOfBoundsColor parameter to allow customisation of the "background" color when the View is zoomed with negative scale or id dragged out of bounds.

This is achieved by wrapping the content in a ZStack with infinite frame and no safe area edges.

I've also updated the readme both to provide an example of this addition and to specify supported platforms and that not only Views of type Image are supported.

Hope everything is okay and that this is an addition you're interested for your project.

2023-11-14 00:28 UTC, ryohey requested changes
Thanks for the contribution! The updated README is perfect. One point though, the addition of outOfBoundsColor changes the size of the View using zoomable(), which may be a destructive change for those who don't need the full screen view. Can you please make the code not change the existing behavior? I haven't tried running it, but perhaps the following code would work.

```swift
@ViewBuilder
func zoomable(
    minZoomScale: CGFloat = 1,
    doubleTapZoomScale: CGFloat = 3
) {
    ...
}

@ViewBuilder
func zoomable(
    minZoomScale: CGFloat = 1,
    doubleTapZoomScale: CGFloat = 3,
    outOfBoundsColor: Color
) -> some View {
    GeometryReader { proxy in
        ZStack {
            outOfBoundsColor
            self.zoomable(
                minZoomScale: minZoomScale,
                doubleTapZoomScale: doubleTapZoomScale
            )
        }
    }
    .frame(maxWidth: .infinity, maxHeight: .infinity)
    .edgesIgnoringSafeArea(.all)
}
```

2023-11-14 03:56 UTC, cdf1982 commented
Thank you for considering this.

Turns out that

```swift
.frame(maxWidth: .infinity, maxHeight: .infinity)
.edgesIgnoringSafeArea(.all)
```

wasn't really necessary.

With today's [693992f](https://github.com/ryohey/Zoomable/commit/693992fac02c1a0e563ffeb6842d30b79f092552) commit I don't think the behavior should break for existing Users: the ZStack would use the default .clear color, but if it's still a breaking change I could wrap the implementation in a check of outOfBoundsColor, leaving the original code unchanged when it's clear.

2023-11-15 07:23 UTC, ryohey reviewed
Thank you! However, using GeometryReader in certain situations disrupts the layout. Could you consider separating the outOfBoundsColor implementation from ZoomableModifier.body, as I suggested?

2023-11-17 14:33 UTC, cdf1982 commented
Hi! I have just committed your suggested implementation, thank you for your patience.

There is a slight difference in behavior when the Zoomable modifier is used on a View that is the destination of a NavigationStack: with this approach, it's necessary to also add a .background() modifier to such view to avoid a different color behind the Navigation Bar, but it's not a problem.

2023-11-18 00:52 UTC, ryohey approved these changes
Thanks! This is perfect.

2023-11-18 00:52 UTC, merged